name: Push Coffe
run-name: ${{ github.actor }} is drinking an coffe ☕

on: 
  push:
    branches: ['master']


jobs:
  push_coffe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
      - name: Coffe setup
        run: |
          echo "An coffe was pushed ☕"
          echo "${{ github.actor }} Has ended his coffe 😋"
          npm list --depth=0 | grep '├─' | awk -F'@' '{print $1 "@" $2}' > reqs.txt
          echo "Installed Cup Dependencies 🧋"


